from dotenv import load_dotenv
load_dotenv(dotenv_path=".env.local")  # take environment variables from .env.local
import json
import requests
import csv
import os
from datetime import datetime
from collections import defaultdict

if not os.path.exists("data"):
    os.makedirs("data")

GITHUB_PAT = os.getenv("GITHUB_PAT")

# GitHub Authentication function
def github_auth(url, lsttoken, ct):
    """
    Authenticate and make a GitHub API request with token rotation.
    """
    jsonData = None
    try:
        ct = ct % len(lsttoken)
        headers = {'Authorization': 'Bearer {}'.format(lsttoken[ct])}
        request = requests.get(url, headers=headers)
        jsonData = json.loads(request.content)
        ct += 1
    except Exception as e:
        print(f"Error during authentication: {e}")
    return jsonData, ct

def get_file_commit_history(repo, filepath, lsttokens):
    """
    Retrieves the complete commit history for a specific file.
    Returns list of commits with author, date, and other details.
    """
    commits_data = []
    ipage = 1
    ct = 0
    
    try:
        while True:
            spage = str(ipage)
            # Get commits that touched this specific file
            commitsUrl = f'https://api.github.com/repos/{repo}/commits?path={filepath}&page={spage}&per_page=100'
            jsonCommits, ct = github_auth(commitsUrl, lsttokens, ct)
            
            if not jsonCommits or len(jsonCommits) == 0:
                break
            
            for commit in jsonCommits:
                try:
                    commit_data = {
                        'sha': commit.get('sha', ''),
                        'author': commit.get('commit', {}).get('author', {}).get('name', 'Unknown'),
                        'author_email': commit.get('commit', {}).get('author', {}).get('email', 'Unknown'),
                        'date': commit.get('commit', {}).get('author', {}).get('date', 'Unknown'),
                        'message': commit.get('commit', {}).get('message', '').split('\n')[0]  # First line only
                    }
                    commits_data.append(commit_data)
                except Exception as e:
                    print(f"Error parsing commit: {e}")
            
            ipage += 1
    except Exception as e:
        print(f"Error fetching commit history for {filepath}: {e}")
    
    return commits_data

def extract_author_info(commits_data):
    """
    Extracts unique authors and their contribution dates for a file.
    Returns authors list and dates list.
    """
    authors_dict = defaultdict(list)  # author -> list of dates
    
    for commit in commits_data:
        author = commit['author']
        date = commit['date'].split('T')[0] if 'T' in commit['date'] else commit['date']  # Extract date part
        if author not in authors_dict:
            authors_dict[author] = []
        authors_dict[author].append(date)
    
    # Create lists of unique authors and dates
    authors = list(authors_dict.keys())
    all_dates = []
    for dates in authors_dict.values():
        all_dates.extend(dates)
    all_dates = sorted(list(set(all_dates)))
    
    return authors, all_dates

def main():
    # GitHub repo
    repo = 'scottyab/rootbeer'
    # repo = 'Skyscanner/backpack'
    # repo = 'k9mail/k-9'
    # repo = 'mendhak/gpslogger'
    
    # Authentication tokens
    lstTokens = [GITHUB_PAT]
    
    file = repo.split('/')[1]
    
    # Read the CSV file generated by FinnWant_collect_files.py
    input_file = f'data/file_{file}.csv'
    
    if not os.path.exists(input_file):
        print(f"Error: Input file {input_file} not found.")
        print("Please run FinnWant_collect_files.py first to generate the file list.")
        return
    
    print(f"Reading source files from {input_file}...")
    
    # Store file information
    files_data = []
    
    try:
        with open(input_file, 'r') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                filepath = row['Filename']
                touches = int(row['Touches'])
                
                print(f"\nProcessing file: {filepath}")
                
                # Get commit history for this file
                commits = get_file_commit_history(repo, filepath, lstTokens)
                authors, dates = extract_author_info(commits)
                
                file_info = {
                    'filepath': filepath,
                    'authors': '; '.join(authors) if authors else 'Unknown',
                    'dates': '; '.join(dates) if dates else 'Unknown',
                    'touch_count': touches,
                    'unique_authors': len(authors),
                    'unique_dates': len(dates),
                    'first_date': min(dates) if dates else 'Unknown',
                    'last_date': max(dates) if dates else 'Unknown'
                }
                
                files_data.append(file_info)
                print(f"  - Authors: {len(authors)}")
                print(f"  - Changes: {touches}")
                print(f"  - Date range: {file_info['first_date']} to {file_info['last_date']}")
    
    except Exception as e:
        print(f"Error reading input file: {e}")
        return
    
    # Output to CSV file
    output_file = f'data/authors_file_touches_{file}.csv'
    
    try:
        with open(output_file, 'w', newline='') as csvfile:
            fieldnames = [
                'File Path',
                'Authors',
                'First Change Date',
                'Last Change Date',
                'All Change Dates',
                'Number of Touches',
                'Number of Unique Authors',
                'Number of Unique Dates'
            ]
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            
            for file_info in files_data:
                writer.writerow({
                    'File Path': file_info['filepath'],
                    'Authors': file_info['authors'],
                    'First Change Date': file_info['first_date'],
                    'Last Change Date': file_info['last_date'],
                    'All Change Dates': file_info['dates'],
                    'Number of Touches': file_info['touch_count'],
                    'Number of Unique Authors': file_info['unique_authors'],
                    'Number of Unique Dates': file_info['unique_dates']
                })
        
        print(f"\n✓ Results saved to: {output_file}")
    
    except Exception as e:
        print(f"Error writing output file: {e}")
        return
    
    # Print summary statistics
    print(f"\n{'='*80}")
    print("SUMMARY STATISTICS")
    print(f"{'='*80}")
    print(f"Total files analyzed: {len(files_data)}")
    
    total_touches = sum(f['touch_count'] for f in files_data)
    
    # Collect unique authors from all files
    all_authors = set()
    for f in files_data:
        if f['authors'] != 'Unknown':
            authors_list = f['authors'].split('; ')
            all_authors.update(authors_list)
    total_authors = len(all_authors)
    
    print(f"Total file touches: {total_touches}")
    print(f"Estimated unique authors: {total_authors}")
    
    # Find files with most changes
    print(f"\nTop 10 Most Changed Files:")
    sorted_files = sorted(files_data, key=lambda x: x['touch_count'], reverse=True)[:10]
    for i, file_info in enumerate(sorted_files, 1):
        print(f"  {i}. {file_info['filepath']}: {file_info['touch_count']} touches, {file_info['unique_authors']} authors")
    
    print(f"\n{'='*80}")

if __name__ == "__main__":
    main()
