import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Import the data from csv generated by authors_file_touches script
df = pd.read_csv('data/authors_touches_rootbeer.csv')

#convert raw dates into, weeks since first source file change
df['Date'] = pd.to_datetime(df['Date'])
start_date = df['Date'].min()
df['Weeks'] = (df['Date'] - start_date).dt.days / 7

#tried to make plot fit and look ok
plt.figure(figsize = (15,7))

#color gradient for authors
unique_authors = df['Author'].unique()
num_authors = len(unique_authors)
cmap = plt.colormaps['tab20']
colors = cmap(np.linspace(0, 1, num_authors))

#Create the scatterplot
for i, (author, group) in enumerate(df.groupby('Author')):
    plt.scatter(group['Weeks'], group['Filename'], label=author, color = colors[i] ,s=25)

#Add labels and display the graph
plt.title('Changes to source files of rootbeer repository')
plt.xlabel('Weeks')
plt.ylabel('Source Files')
plt.grid(True)
plt.legend(title='Author')
plt.legend(loc='upper left', bbox_to_anchor = (1,1))
plt.tight_layout()

plt.savefig('JustinS170_file_activity.png', dpi = 300, bbox_inches = 'tight')